{
  "steps": [
    {
      "name": "gcr.io/cloud-builders/npm",
      "args": ["ci"]
    },
    {
      "name": "gcr.io/cloud-builders/npm",
      "args": ["run", "build"]
    },
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": ["build", "-t", "gcr.io/$PROJECT_ID/election-assistant", "."]
    },
    {
      "name": "gcr.io/cloud-builders/docker",
      "args": ["push", "gcr.io/$PROJECT_ID/election-assistant"]
    },
    {
      "name": "gcr.io/cloud-builders/gke-deploy",
      "args": [
        "run",
        "--filename=k8s/",
        "--image=gcr.io/$PROJECT_ID/election-assistant",
        "--location=us-central1",
        "--cluster=election-assistant-cluster"
      ]
    }
  ],
  "images": [
    "gcr.io/$PROJECT_ID/election-assistant"
  ],
  "options": {
    "machineType": "N1_HIGHCPU_8"
  },
  "timeout": "1800s"
}
